stages:
  - name: "checkout"
    steps:
      - checkout: scm
  - name: "build"
    dependsOn: "checkout"
    steps:
      - script: "javac HelloWorld.java"
  - name: "test"
    dependsOn: "build"
    steps:
      - script: "java HelloWorld"
  - name: "deploy"
    dependsOn: "test"
    steps:
      - script: 'echo "Déploiement sur le serveur de production en cours"'

